<<<<<<< HEAD
# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

runtime: custom
env: flex

service: yolov5app

liveness_check:
  initial_delay_sec: 600

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 20
=======
runtime: custom
env: flex

service: yolov5app

liveness_check:
  initial_delay_sec: 600

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 20
>>>>>>> 37e22266 (Fist commit)
