#!/bin/bash -l

#$ -P ec500bn
#$ -j y
#$ -N yolov5
#$ -o logs/yolo.qlog

#$ -l h_rt=24:00:00
#$ -pe omp 4

#$ -l gpus=1
#$ -l gpu_c=7.0

# updated dino env combining dino reqs with breast-CLIP-downstream reqs
module load python3
source .venv/bin/activate

# train
python train.py --img 640 --batch 16 --epochs 50 --data coco.yaml --weights yolov5s.pt --cache disk

# eval
python val.py --weights runs/train/exp3/weights/best.pt --data coco.yaml --img 640