# Ultralytics ðŸš€ AGPL-3.0 License - https://ultralytics.com/license

name: ðŸ› Bug Report
description: "Problems with Ultralytics YOLOv5"
labels: [bug, triage]
type: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an Ultralytics YOLOv5 ðŸ› Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the Ultralytics YOLOv5 [docs](https://docs.ultralytics.com/yolov5/) and [issues](https://github.com/ultralytics/yolov5/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched https://github.com/ultralytics/yolov5/issues and did not find a similar report.
          required: true

  - type: dropdown
    attributes:
      label: Project area
      description: |
        Help us route the report to the right maintainers.
      multiple: true
      options:
        - "Training"
        - "Validation/testing"
        - "Export/deployment"
        - "Models/checkpoints"
        - "Documentation"
        - "Other"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug
      description: Please describe the issue in detail so we can reproduce it in Ultralytics YOLOv5. Include logs, screenshots, console output, and any context that helps explain the problem.
      placeholder: |
        ðŸ’¡ ProTip! Include as much information as possible (logs, tracebacks, screenshots, etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Share the platform and version information relevant to your report.
      placeholder: |
        Please include:
        - OS (e.g., Ubuntu 20.04, macOS 13.5, Windows 11)
        - Language or framework version (Python, Swift, Flutter, etc.)
        - Package or app version
        - Hardware (e.g., CPU, GPU model, device model)
        - Any other environment details
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        Provide the smallest possible snippet, command, or steps required to reproduce the issue. This helps us pinpoint problems faster.
      placeholder: |
        ```python
        # Code or commands to reproduce your issue here
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/ultralytics/yolov5/pulls) to help improve Ultralytics YOLOv5, especially if you know how to fix the issue.
        See the Ultralytics [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!
