# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: 🚀 Feature Request
description: "Suggest an Ultralytics YOLOv5 improvement"
labels: [enhancement]
type: "feature"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an Ultralytics YOLOv5 🚀 Feature Request!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the Ultralytics YOLOv5 [docs](https://docs.ultralytics.com/yolov5/) and [issues](https://github.com/ultralytics/yolov5/issues) to see if a similar feature request already exists.
      options:
        - label: >
            I have searched https://github.com/ultralytics/yolov5/issues and did not find a similar request.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: Briefly describe the feature you would like to see added to Ultralytics YOLOv5.
      placeholder: |
        What new capability or improvement are you proposing?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case
      description: Explain how this feature would be used and who benefits from it. Screenshots or mockups are welcome.
      placeholder: |
        How would this feature improve your workflow?

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/ultralytics/yolov5/pulls) to help improve Ultralytics YOLOv5.
        See the Ultralytics [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!
