# Ultralytics ðŸš€ AGPL-3.0 License - https://ultralytics.com/license

name: â“ Question
description: "Ask an Ultralytics YOLOv5 question"
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for asking an Ultralytics YOLOv5 â“ Question!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the Ultralytics YOLOv5 [docs](https://docs.ultralytics.com/yolov5/), [issues](https://github.com/ultralytics/yolov5/issues), and [Ultralytics discussions](https://github.com/orgs/ultralytics/discussions) to see if a similar question already exists.
      options:
        - label: >
            I checked the docs, issues, and discussions and could not find an answer.
          required: true

  - type: textarea
    attributes:
      label: Question
      description: What is your question? Provide as much detail as possible so we can assist with Ultralytics YOLOv5. Include code snippets, screenshots, logs, or links to notebooks/demos.
      placeholder: |
        ðŸ’¡ ProTip! Include as much information as possible (logs, tracebacks, screenshots, etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?
